MODEL:
  DEFORM_CONV: True
#  PRE_TRAIN: outputs/RCAN_x4_Apr0622_1315/model/model_best.pth.tar
DATASET:
  DATA_SCALE: [4]
  OUT_PATCH_SIZE: 192
  DATA_RANGE: [[1, 800], [801, 805]]
LOG:
  SAVE: RCAN_x4
#  LOAD: RCAN_x4_Apr0622_1315
SOLVER:
  TEST_EVERY: 20